version: "3"

services:
  python_wimp:
    build: .
    container_name: python_wimp
    restart: always
    networks:
      - metakgp-wiki_main_network

networks:
  metakgp-wiki_main_network:
    external: true